### ISSUE TITLE
找不到包 Microsoft.DotNet.Interactive.VisualStudio

### ISSUE THREAD

**Issue by fan0217** [AIDotNet/EasyAgent#1]
找不到包 Microsoft.DotNet.Interactive.VisualStudio

**Comment by xuzeyu91** [comment]
> 找不到包 Microsoft.DotNet.Interactive.VisualStudio

需要升级Visual studio为最新版本

**Comment by fan0217** [comment]
我的VS肯定是最新的
&nbsp;


Fans
***@***.***



&nbsp;

**Comment by xuzeyu91** [comment]
你的vs目前是什么版本？
